# Generated by Django 4.2.7 on 2023-11-11 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crimeDetect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='log_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
